import { createHash } from "node:crypto";
import { createReadStream } from "node:fs";
import { mkdir, rename, rm, rmdir, stat } from "node:fs/promises";
import path from "node:path";
import { Transform, type Readable } from "node:stream";
import { pipeline } from "node:stream/promises";
import { createWriteStream } from "node:fs";
import { HttpError } from "./errors";

/** Where attachment bytes live. Only the filesystem driver exists; S3-style drivers fit the same interface. */
export interface StorageDriver {
  /** Streams `body` to `key`, hashing it on the way. Rejects with 413 past `maxBytes`, leaving nothing behind. */
  put(key: string, body: Readable, maxBytes: number): Promise<{ size: number; sha256: string }>;
  open(key: string): Promise<{ stream: Readable; size: number }>;
  remove(key: string): Promise<void>;
}

const KEY_PATTERN = /^[A-Za-z0-9_-]+(\/[A-Za-z0-9_-]+)*$/;

export class FileSystemStorage implements StorageDriver {
  constructor(private readonly root: string) {}

  private resolve(key: string) {
    // Keys are generated by the server, but never trust a path that reaches the filesystem.
    if (!KEY_PATTERN.test(key)) throw new Error(`Invalid storage key: ${key}`);
    return path.join(this.root, key);
  }

  async put(key: string, body: Readable, maxBytes: number) {
    const target = this.resolve(key);
    const partial = `${target}.part`;
    await mkdir(path.dirname(target), { recursive: true });

    const hash = createHash("sha256");
    let size = 0;
    const meter = new Transform({
      transform(chunk: Buffer, _encoding, callback) {
        size += chunk.length;
        if (size > maxBytes) return callback(new HttpError(413, "File too large"));
        hash.update(chunk);
        callback(null, chunk);
      },
    });

    try {
      await pipeline(body, meter, createWriteStream(partial, { flags: "wx" }));
      await rename(partial, target);
    } catch (error) {
      await rm(partial, { force: true });
      throw error;
    }
    return { size, sha256: hash.digest("hex") };
  }

  async open(key: string) {
    const file = this.resolve(key);
    const { size } = await stat(file);
    return { stream: createReadStream(file), size };
  }

  async remove(key: string) {
    const file = this.resolve(key);
    await rm(file, { force: true });
    // Drop the project folder once its last file is gone (rmdir refuses a non-empty folder).
    if (key.includes("/")) await rmdir(path.dirname(file)).catch(() => undefined);
  }
}

let storage: StorageDriver | undefined;

/** Root of the upload volume (`UPLOAD_DIR`; a Docker volume in production). */
export const uploadRoot = () =>
  path.resolve(/* turbopackIgnore: true */ process.env.UPLOAD_DIR ?? "./data/uploads");

/** Shared driver configured through `UPLOAD_DIR`. */
export function getStorage(): StorageDriver {
  return (storage ??= new FileSystemStorage(uploadRoot()));
}

export const maxUploadBytes = () => Number(process.env.UPLOAD_MAX_MB ?? 50) * 1024 * 1024;
